### ISSUE TITLE
In homepage, buttons in the header are small and improve css

### ISSUE THREAD

**Issue by khushiiagrawal** [bpmn-io/bpmn.io#205] opened 2024-10-10 05:34 UTC
### Is your feature request related to a problem? Please describe.

The buttons which are there in the header of the homepage are not matching with the font of the homepage and they are small for the viewer.
Because of which it is showing that the website is lagging in managing the font./

### Solution

I would like to improve the css of the homepage and also would increase the font size 

### Describe alternatives you've considered

You can keep it as it is.

### Additional context
<img width="1290" alt="Screenshot 2024-10-10 at 11 03 57 AM" src="https://github.com/user-attachments/assets/f245c5a6-d8e2-475d-bf3f-57298e33410b">

**Comment by vsgoulart** [comment] 2024-10-10 08:26
@nikku I transfered this issue to here from the `form-js` repo
I think it makes more sense here

**Comment by khushiiagrawal** [comment] 2024-10-11 05:38
@nikku  yea the font looks small there and it isn't going with the homepage also

**Comment by nikku** [comment] 2024-10-11 06:23
@khushiiagrawal Both pages use _exactly_ the same font, as intended, and this is the standard font size for Bootstrap@4 sites:

![capture 0qUpVG_optimized](https://github.com/user-attachments/assets/a20aa530-2996-473e-98d1-74f9f1ac8787)

Closing your issue as _cannot reproduce_. Happy to re-open if we're able to reproduce this in any way or form.

**Closed by nikku** 2024-10-11 06:23 UTC
Labels: enhancement
